source 'https://rubygems.org'

gem 'state_machine', '0.9.3'

# gem 'strong_parameters'

gem 'rails', '4.1.4'

gem 'rails-api'

gem 'spring', :group => :development

gem 'sqlite3'
gem 'foreigner'
gem 'active_model_serializers'

gem 'pry-rails'

gem 'kaminari'
gem 'test-unit'
gem 'rack-cors', :require => 'rack/cors'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'bcrypt', '~> 3.1.7'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
